### ISSUE TITLE
TrainTest.csv and Predict.csv do not contains ['diff1', 'diff4', 'diff2', 'diff3'] columns

### ISSUE THREAD

**Issue by iamaffifa** [neilay-khasnabish/COVID-19#1]
Greetings,
as a first step COVID_Data_Pre_JHop.py successfully generated TrainTest.csv and Predict.csv. While running COVID_Prediction.py, its providing me with the key error for column names ['diff1', 'diff4', 'diff2', 'diff3'].  Actually these columns are not present in TrainTest.csv and Predict.csv. Thank You
![keyError](https://user-images.githubusercontent.com/36693344/78532937-7fa45d00-7801-11ea-8ea5-bd7a3f5d1268.png)
![Predict csv](https://user-images.githubusercontent.com/36693344/78532942-80d58a00-7801-11ea-81bf-dbdcc0dc966d.png)
![TrainTest csv](https://user-images.githubusercontent.com/36693344/78532943-816e2080-7801-11ea-9e3d-1844cb76c925.png)

**Comment by neilay-khasnabish** [comment]
The script is updated.

**Comment by neilay-khasnabish** [comment]
Script is updated. Thanks for the observation.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
